export type MediaKind = "movie" | "series" | "dubbed";

export type Media = {
  id: string;
  kind: MediaKind;
  title: string;
  titleKu: string;
  overview: string;
  overviewKu: string;
  year: number;
  rating: number; // 0-10
  duration: string; // "2h 15m" or "3 Seasons"
  genres: string[];
  genresKu: string[];
  poster: string; // portrait
  backdrop: string; // wide
  videoUrl: string;
  featured?: boolean;
  seasons?: number;
};

// Free CC / test videos so playback actually works
const BBB = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4";
const ED = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4";
const SINTEL = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4";
const TOS = "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4";

const img = (id: string) => `https://image.tmdb.org/t/p/w780${id}`;
const wide = (id: string) => `https://image.tmdb.org/t/p/w1280${id}`;

export const media: Media[] = [
  {
    id: "dune-2",
    kind: "movie",
    title: "Dune: Part Two",
    titleKu: "دیون: بەشی دووەم",
    overview:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    overviewKu:
      "پۆڵ ئاترەیدیس لەگەڵ چانی و فرێمەن یەکدەگرێت بۆ تۆڵەسەندنەوە لەو کەسانەی خێزانەکەی لەناوبردووە.",
    year: 2024,
    rating: 8.5,
    duration: "2h 46m",
    genres: ["Sci-Fi", "Adventure"],
    genresKu: ["زانستی خەیاڵی", "سەرکێشی"],
    poster: img("/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg"),
    backdrop: wide("/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg"),
    videoUrl: BBB,
    featured: true,
  },
  {
    id: "oppenheimer",
    kind: "movie",
    title: "Oppenheimer",
    titleKu: "ئۆپنهایمەر",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    overviewKu: "چیرۆکی ڕۆڵی ڕۆبێرت ئۆپنهایمەر لە دروستکردنی بۆمبی ئەتۆمی لە جەنگی جیهانی دووەم.",
    year: 2023,
    rating: 8.3,
    duration: "3h 0m",
    genres: ["Drama", "History"],
    genresKu: ["دراما", "مێژوو"],
    poster: img("/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg"),
    backdrop: wide("/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg"),
    videoUrl: TOS,
  },
  {
    id: "interstellar",
    kind: "movie",
    title: "Interstellar",
    titleKu: "نێوان ئەستێرەیی",
    overview:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    overviewKu: "تیمێک لە گەڕۆکان بەناو کونە کرمیدا دەگەڕێن بۆ ڕزگارکردنی مرۆڤایەتی.",
    year: 2014,
    rating: 8.7,
    duration: "2h 49m",
    genres: ["Sci-Fi", "Drama"],
    genresKu: ["زانستی خەیاڵی", "دراما"],
    poster: img("/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg"),
    backdrop: wide("/pbrkL804c8yAv3zBZR4QPEafpAR.jpg"),
    videoUrl: ED,
  },
  {
    id: "the-batman",
    kind: "movie",
    title: "The Batman",
    titleKu: "بەتمان",
    overview:
      "Batman uncovers corruption in Gotham while pursuing the Riddler, a killer targeting the elite.",
    overviewKu: "بەتمان گەندەڵی لە گۆتام ئاشکرا دەکات لە کاتی ڕاوکردنی ڕیدلەردا.",
    year: 2022,
    rating: 7.8,
    duration: "2h 56m",
    genres: ["Action", "Crime"],
    genresKu: ["ئاکشن", "تاوان"],
    poster: img("/74xTEgt7R36Fpooo50r9T25onhq.jpg"),
    backdrop: wide("/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg"),
    videoUrl: SINTEL,
  },
  {
    id: "john-wick-4",
    kind: "movie",
    title: "John Wick: Chapter 4",
    titleKu: "جۆن ویک ٤",
    overview: "John Wick uncovers a path to defeating the High Table.",
    overviewKu: "جۆن ویک ڕێگا دەدۆزێتەوە بۆ بەزاندنی مێزە بەرزەکە.",
    year: 2023,
    rating: 7.7,
    duration: "2h 49m",
    genres: ["Action", "Thriller"],
    genresKu: ["ئاکشن", "سەرنجڕاکێش"],
    poster: img("/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg"),
    backdrop: wide("/7I6VUdPj6tQECNHdviJkUHD2u89.jpg"),
    videoUrl: BBB,
  },
  {
    id: "spiderverse",
    kind: "movie",
    title: "Across the Spider-Verse",
    titleKu: "بەناو جیهانی جاڵجاڵۆکەدا",
    overview: "Miles Morales catapults across the Multiverse.",
    overviewKu: "مایلز مۆرالیس بەناو زۆر جیهاندا دەفڕێت.",
    year: 2023,
    rating: 8.6,
    duration: "2h 20m",
    genres: ["Animation", "Action"],
    genresKu: ["کارتۆن", "ئاکشن"],
    poster: img("/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg"),
    backdrop: wide("/4HodYYKEIsGOdinkGi2Ucfxa9Xs.jpg"),
    videoUrl: ED,
  },

  // Series
  {
    id: "stranger-things",
    kind: "series",
    title: "Stranger Things",
    titleKu: "شتە نامۆکان",
    overview: "Kids in a small town uncover supernatural mysteries and government experiments.",
    overviewKu: "منداڵانێک لە شارۆچکەیەکدا نهێنی سروشتی و تاقیکاریی حکومەت ئاشکرا دەکەن.",
    year: 2016,
    rating: 8.7,
    duration: "4 Seasons",
    seasons: 4,
    genres: ["Drama", "Horror"],
    genresKu: ["دراما", "ترسناک"],
    poster: img("/49WJfeN0moxb9IPfGn8AIqMGskD.jpg"),
    backdrop: wide("/56v2KjBlU4XaOv9rVYEQypROD7P.jpg"),
    videoUrl: SINTEL,
    featured: true,
  },
  {
    id: "breaking-bad",
    kind: "series",
    title: "Breaking Bad",
    titleKu: "بریکینگ باد",
    overview: "A chemistry teacher turns to making meth after a cancer diagnosis.",
    overviewKu: "مامۆستایەکی کیمیا دەبێت بە دروستکەری مادەی هۆشبەر دوای نەخۆشی شێرپەنجە.",
    year: 2008,
    rating: 9.5,
    duration: "5 Seasons",
    seasons: 5,
    genres: ["Crime", "Drama"],
    genresKu: ["تاوان", "دراما"],
    poster: img("/ggFHVNu6YYI5L9pCfOacjizRGt.jpg"),
    backdrop: wide("/tsRy63Mu5cu022Q9OggLruXAA9I.jpg"),
    videoUrl: TOS,
  },
  {
    id: "the-crown",
    kind: "series",
    title: "The Crown",
    titleKu: "تاجەکە",
    overview: "The reign of Queen Elizabeth II through the decades.",
    overviewKu: "پاشایەتی شاژنە ئێلیزابێت دووەم بەدرێژایی دەیەکان.",
    year: 2016,
    rating: 8.6,
    duration: "6 Seasons",
    seasons: 6,
    genres: ["Drama", "History"],
    genresKu: ["دراما", "مێژوو"],
    poster: img("/1M876KPjulVwppEpldhdc8V4o68.jpg"),
    backdrop: wide("/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg"),
    videoUrl: BBB,
  },
  {
    id: "house-of-dragon",
    kind: "series",
    title: "House of the Dragon",
    titleKu: "ماڵی ئەژدیها",
    overview: "The Targaryen civil war, 200 years before Game of Thrones.",
    overviewKu: "شەڕی ناوخۆیی تارگاریان، دوو سەد ساڵ پێش گەیمی ئۆف ترۆنز.",
    year: 2022,
    rating: 8.4,
    duration: "2 Seasons",
    seasons: 2,
    genres: ["Fantasy", "Drama"],
    genresKu: ["خەیاڵی", "دراما"],
    poster: img("/z2yahl2uefxDCl0nogcRBstwruJ.jpg"),
    backdrop: wide("/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg"),
    videoUrl: ED,
  },
  {
    id: "the-bear",
    kind: "series",
    title: "The Bear",
    titleKu: "ورچەکە",
    overview: "A young chef runs his late brother's chaotic sandwich shop.",
    overviewKu: "چێشتلێنەرێکی گەنج دووکانی برا مردووەکەی بەڕێوە دەبات.",
    year: 2022,
    rating: 8.6,
    duration: "3 Seasons",
    seasons: 3,
    genres: ["Comedy", "Drama"],
    genresKu: ["کۆمیدی", "دراما"],
    poster: img("/zPyHitkG1FpXBQZ7wSXBmpTFbrl.jpg"),
    backdrop: wide("/9x50vGWMKMwWPeZpHrIw2AcRSPl.jpg"),
    videoUrl: SINTEL,
  },
  {
    id: "arcane",
    kind: "series",
    title: "Arcane",
    titleKu: "ئارکەین",
    overview: "Sisters torn apart by the tension between two cities of Piltover and Zaun.",
    overviewKu: "دوو خوشک بەهۆی ملمالنێی نێوان دوو شارەوە لێکدەبنەوە.",
    year: 2021,
    rating: 9.0,
    duration: "2 Seasons",
    seasons: 2,
    genres: ["Animation", "Action"],
    genresKu: ["کارتۆن", "ئاکشن"],
    poster: img("/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg"),
    backdrop: wide("/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg"),
    videoUrl: TOS,
  },

  // Dubbed
  {
    id: "avatar-dubbed",
    kind: "dubbed",
    title: "Avatar: The Way of Water (Kurdish Dub)",
    titleKu: "ئەڤاتار: ڕێگای ئاو (دۆبلاژی کوردی)",
    overview: "Jake Sully lives with his newfound family on Pandora. Kurdish dubbed version.",
    overviewKu: "جەیک سەلی لەگەڵ خێزانە نوێکەی لە پەندۆرا دەژی. دۆبلاژکراوە بۆ کوردی.",
    year: 2022,
    rating: 7.6,
    duration: "3h 12m",
    genres: ["Sci-Fi", "Adventure"],
    genresKu: ["زانستی خەیاڵی", "سەرکێشی"],
    poster: img("/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg"),
    backdrop: wide("/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg"),
    videoUrl: BBB,
  },
  {
    id: "top-gun-dubbed",
    kind: "dubbed",
    title: "Top Gun: Maverick (Kurdish Dub)",
    titleKu: "تۆپ گەن: ماڤریک (دۆبلاژی کوردی)",
    overview: "Maverick trains a new generation of Top Gun pilots. Kurdish dubbed version.",
    overviewKu: "ماڤریک نەوەیەکی نوێی فڕۆکەوانان ڕاهێنان دەکات. دۆبلاژی کوردی.",
    year: 2022,
    rating: 8.3,
    duration: "2h 11m",
    genres: ["Action", "Drama"],
    genresKu: ["ئاکشن", "دراما"],
    poster: img("/62HCnUTziyWcpDaBO2i1DX17ljH.jpg"),
    backdrop: wide("/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg"),
    videoUrl: ED,
  },
  {
    id: "frozen-dubbed",
    kind: "dubbed",
    title: "Frozen II (Kurdish Dub)",
    titleKu: "فرۆزن ٢ (دۆبلاژی کوردی)",
    overview: "Elsa and Anna journey into the unknown. Kurdish dubbed version.",
    overviewKu: "ئێلسا و ئانا بەرەو شوێنی نەناسراو دەڕۆن. دۆبلاژی کوردی.",
    year: 2019,
    rating: 6.8,
    duration: "1h 43m",
    genres: ["Animation", "Family"],
    genresKu: ["کارتۆن", "خێزانی"],
    poster: img("/mINJaa34MtknCYl5AjtNJzWj8cD.jpg"),
    backdrop: wide("/2Fp2ZzHYCjhLPnp1jjMgvfyPHnZ.jpg"),
    videoUrl: SINTEL,
  },
  {
    id: "lion-king-dubbed",
    kind: "dubbed",
    title: "The Lion King (Kurdish Dub)",
    titleKu: "پاشای شێرەکان (دۆبلاژی کوردی)",
    overview: "Simba idolizes his father and takes to heart his own royal destiny. Kurdish dub.",
    overviewKu: "سیمبا باوکی دەپەرستێت و چارەنووسی شاهانەی خۆی وەردەگرێت. دۆبلاژی کوردی.",
    year: 2019,
    rating: 6.9,
    duration: "1h 58m",
    genres: ["Animation", "Family"],
    genresKu: ["کارتۆن", "خێزانی"],
    poster: img("/dzBtMocZuJbjLOXvrl4zGYigDzh.jpg"),
    backdrop: wide("/pIUvQ9Ed35wlWhY2oU6OmwEsmzG.jpg"),
    videoUrl: TOS,
  },
  {
    id: "fast-x-dubbed",
    kind: "dubbed",
    title: "Fast X (Kurdish Dub)",
    titleKu: "فاست ١٠ (دۆبلاژی کوردی)",
    overview: "Dom Toretto faces his most lethal opponent. Kurdish dubbed version.",
    overviewKu: "دۆم تۆرێتۆ ڕووبەڕووی مەترسیدارترین دوژمنی دەبێتەوە. دۆبلاژی کوردی.",
    year: 2023,
    rating: 6.8,
    duration: "2h 21m",
    genres: ["Action", "Crime"],
    genresKu: ["ئاکشن", "تاوان"],
    poster: img("/fiVW06jE7z9YnO4trhaMEdclSiC.jpg"),
    backdrop: wide("/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg"),
    videoUrl: BBB,
  },
];

export const getById = (id: string) => media.find((m) => m.id === id);
export const byKind = (k: MediaKind) => media.filter((m) => m.kind === k);
export const featured = () => media.find((m) => m.featured) ?? media[0];
export const trending = () => [...media].sort((a, b) => b.rating - a.rating).slice(0, 8);
